SET 'auto.offset.reset' = 'earliest';

CREATE STREAM PRODUCTS_STREAM (
    product_id STRING,
    name STRING)
WITH (
    KAFKA_TOPIC='products',
    KEY_FORMAT='KAFKA',
    VALUE_FORMAT='AVRO');

CREATE TABLE PRODUCTS_NAME_ID_MAP_TABLE AS
SELECT 
    name as product_name,
    LATEST_BY_OFFSET(product_id) AS product_id
FROM PRODUCTS_STREAM
GROUP BY name
EMIT CHANGES;

CREATE TABLE PRODUCTS_LIST AS
SELECT 'all' AS KEY,
COLLECT_SET(name) as products
FROM PRODUCTS_STREAM
GROUP BY 'all';

CREATE STREAM USER_ACTIONS_STREAM (
    user_id STRING,
    searched_product_name STRING)
WITH (
    KAFKA_TOPIC='client-actions',
    KEY_FORMAT='KAFKA',
    VALUE_FORMAT='AVRO');

CREATE TABLE USERS_SEEN_PRODUCTS AS
SELECT 
    USER_ACTIONS_STREAM.user_id,
    COLLECT_SET(PRODUCTS_NAME_ID_MAP_TABLE.product_name) as products,
    'all' as join_hack
FROM USER_ACTIONS_STREAM
INNER JOIN PRODUCTS_NAME_ID_MAP_TABLE on PRODUCTS_NAME_ID_MAP_TABLE.product_name = USER_ACTIONS_STREAM.searched_product_name
GROUP BY USER_ACTIONS_STREAM.user_id
EMIT CHANGES;

CREATE TABLE USERS_RECOMENDATIONS AS
SELECT
    USERS_SEEN_PRODUCTS.user_id,
    ARRAY_EXCEPT(PRODUCTS_LIST.products, USERS_SEEN_PRODUCTS.products) as products
FROM USERS_SEEN_PRODUCTS
JOIN PRODUCTS_LIST on PRODUCTS_LIST.key = USERS_SEEN_PRODUCTS.join_hack
EMIT CHANGES;
