// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Image defines model for Image.
type Image struct {
	Alt *string `json:"alt,omitempty"`
	Url *string `json:"url,omitempty"`
}

// Price defines model for Price.
type Price struct {
	Amount   *float32 `json:"amount,omitempty"`
	Currency *string  `json:"currency,omitempty"`
}

// Product defines model for Product.
type Product struct {
	Brand          *string            `json:"brand,omitempty"`
	Category       *string            `json:"category,omitempty"`
	CreatedAt      *time.Time         `json:"created_at,omitempty"`
	Description    *string            `json:"description,omitempty"`
	Images         *[]Image           `json:"images,omitempty"`
	Index          *string            `json:"index,omitempty"`
	Name           *string            `json:"name,omitempty"`
	Price          *Price             `json:"price,omitempty"`
	ProductId      *string            `json:"product_id,omitempty"`
	Sku            *string            `json:"sku,omitempty"`
	Specifications *map[string]string `json:"specifications,omitempty"`
	Stock          *Stock             `json:"stock,omitempty"`
	StoreId        *string            `json:"store_id,omitempty"`
	Tags           *[]string          `json:"tags,omitempty"`
	UpdatedAt      *time.Time         `json:"updated_at,omitempty"`
}

// Stock defines model for Stock.
type Stock struct {
	Available *int `json:"available,omitempty"`
	Reserved  *int `json:"reserved,omitempty"`
}

// GetProductsByNameParams defines parameters for GetProductsByName.
type GetProductsByNameParams struct {
	// Name Имя продукта
	Name string `form:"name" json:"name"`

	// XUserId Идентификатор пользователя
	XUserId string `json:"X-User-Id"`
}

// GetRecommendationsParams defines parameters for GetRecommendations.
type GetRecommendationsParams struct {
	// XUserId Идентификатор пользователя
	XUserId string `json:"X-User-Id"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить продукты по имени
	// (GET /product)
	GetProductsByName(c *gin.Context, params GetProductsByNameParams)
	// Получить рекомендации для пользователя
	// (GET /recommendations)
	GetRecommendations(c *gin.Context, params GetRecommendationsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetProductsByName operation middleware
func (siw *ServerInterfaceWrapper) GetProductsByName(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductsByNameParams

	// ------------- Required query parameter "name" -------------

	if paramValue := c.Query("name"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument name is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserId = XUserId

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-Id is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductsByName(c, params)
}

// GetRecommendations operation middleware
func (siw *ServerInterfaceWrapper) GetRecommendations(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecommendationsParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserId = XUserId

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-Id is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRecommendations(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/product", wrapper.GetProductsByName)
	router.GET(options.BaseURL+"/recommendations", wrapper.GetRecommendations)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUy27jNhT9FYHt0rGdZqddWxSFgSIwmhZoURQBLV07TCSSoahgjEBAxpnHIgGynV0w",
	"f2AEDkbjxM4vXP7RgJQdxbY8TmY1K0rk5X2cc3hOSSBiKThwnRD/lCTBAcTUfbZi2gP7IZWQoDQDt00j",
	"bRfdl0B8kmjFeI9kNZKqqGI/q813ROcQAm0j24oFVYljkXKXuytUTDXxSTcSVJPHFDyNO6BsiiBVCnjQ",
	"f3ZFEaaBXq3ZUZSHleMEVENPqH71oQKqIdyni+2GVMOWZjGULZd3QkgCxaRmglfmZBZu1xTTELuPHxV0",
	"iU9+aJQcNWYENQp2ymGpUrTv8vAQXlVW4DSGygM5J+RrBQvWXLQDc59VA5ccpdX7EgLWZQG1CBSEhyGz",
	"PzRqL5CycnWFz0SL4GhTw3suqIhWsK5dTXuLoK+r/ghwKsMXkl81wt58hKVHcEJZRDvRU6IY19ArdK8g",
	"AXUCYdXpapXMyaErXDTTNin5l1p9eHtSMa69LuM08n79o/Xb7l/ez+02qZETUInTKNmuN+tNW1VI4FQy",
	"4pOderO+Q2pEUn3g+m3I8mn1wC12HEdyKyQ++R307PUlv/R3qYNHUkVj0KAS4v93uvgyCH7Ae3Pl4YM5",
	"wymOzDmOzQCHxI5CfHKcguqTuZiLxeJynDJlcdEqhdrMxirdoaLeCG9xYgaYmzeY4xiHZoBTc+bhA07x",
	"zlziJ5zijdu+xTtzNe/lAGgIqmzmn62/E1BbrfBFHf3vaJWCJ4UEfmo27RIIrqHwQyplNHs4jcOk8I8y",
	"37PsYu6AK3rOlq2J4PVT5D2c4BA/Fxg5kSVpHFNrjASvHT7n5j3mZmAul0gzFw5BD3O8t7cxd/cbCgIR",
	"x8DD0grWSefPpdDN2vneuNz+Ni43uFAFax/xAXPzGqc49swZ3uIYpzPcR8XIOMGJuTBvPQuJw8CSdbOJ",
	"1JVkQ/MOc8w9HFkA1yObZVn2JQAA//8nrK9kYAgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
